CREATE PROFILE PF_AARCORE 
    LIMIT
        PASSWORD_LIFE_TIME 180
        SESSIONS_PER_USER 3
        FAILED_LOGIN_ATTEMPTS 7
        PASSWORD_LOCK_TIME 1
        PASSWORD_REUSE_TIME 10
        PASSWORD_GRACE_TIME DEFAULT
        CONNECT_TIME 180
        IDLE_TIME 30;
        
        
DROP PROFILE PF_AARCORE CASCADE;


SELECT profile
    FROM dba_profiles
    WHERE profile = 'PF_AARCORE';