CREATE TEMPORARY TABLESPACE TS_AAR_TEMP
    TEMPFILE 'TS_AAR_TEMP.dbf'
    SIZE 7M
    AUTOEXTEND ON NEXT 3M
    MAXSIZE 30M;


DROP TABLESPACE TS_AAR_TEMP
    INCLUDING CONTENTS 
    AND DATAFILES
    CASCADE CONSTRAINTS;
    
    
SELECT tablespace_name
    FROM dba_tablespaces
    WHERE tablespace_name = 'TS_AAR_TEMP';