CREATE ROLE RL_AARCORE;


GRANT CREATE SESSION TO RL_AARCORE;
GRANT CREATE TABLE TO RL_AARCORE;
GRANT CREATE VIEW TO RL_AARCORE;
GRANT CREATE PROCEDURE TO RL_AARCORE;


DROP ROLE RL_AARCORE;


SELECT role
    FROM dba_roles
    WHERE role = 'RL_AARCORE';