ALTER SESSION SET CONTAINER = CDB$ROOT;

DROP USER C##AAR CASCADE;

CREATE USER C##AAR IDENTIFIED BY "CommonPass123" CONTAINER = ALL;

GRANT SET CONTAINER TO C##AAR CONTAINER = ALL;

GRANT CREATE SESSION, CREATE TABLE TO C##AAR CONTAINER = ALL;

GRANT UNLIMITED TABLESPACE TO C##AAR CONTAINER = ALL;